version.prefix=2.1.0
is-preview=false
debug=true
skip_integration_tests=true
java-api-location=https://docs.oracle.com/javase/8/docs/api/
deploy-target.dir=./deploy
test-preparator-docs=./test/docs
installer.executable=makensis
